language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: PANDAS_VERSION=0.16.1 NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1
  - python: 2.7
    env: PANDAS_VERSION=0.17.1 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.15.1
  - python: 3.4
    env: PANDAS_VERSION=0.16.1 NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.15.1
  - python: 3.4
    env: PANDAS_VERSION=0.17.1 NUMPY_VERSION=1.10.2 SCIPY_VERSION=0.15.1

before_install:
  - sed -i "s/numpy==.*/numpy==$NUMPY_VERSION/g" etc/requirements.txt
  - sed -i "s/pandas==.*/pandas==$PANDAS_VERSION/g" etc/requirements.txt
install:
  - pip install --upgrade pip coverage coveralls
  - pip install -r etc/requirements.txt
  - pip install -r etc/requirements_dev.txt
  - pip install -r etc/requirements_blaze.txt  # this uses git requirements right now
  - pip install -e .
before_script:
  - pip freeze | sort
script:
  - nosetests tests/
  - flake8 zipline tests
after_success:
  - coveralls

branches:
  only:
    - master
